- first_start: false
  height: 720
  heroes:
    Abaddon:
    - 0
    - 1
    - 2
    Alchemist:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Ancient Apparition:
    - 0
    - 1
    - 2
    Anti-Mage:
    - 0
    - 1
    - 2
    - 3
    - 4
    Arc Warden:
    - 0
    Axe:
    - 0
    - 1
    - 2
    - 3
    - 4
    Bane:
    - 0
    Batrider:
    - 0
    - 1
    - 2
    - 3
    - 4
    Beastmaster:
    - 0
    - 1
    - 2
    - 3
    - 4
    Bloodseeker:
    - 0
    Bounty Hunter:
    - 0
    - 1
    - 2
    - 3
    Brewmaster:
    - 0
    Bristleback:
    - 0
    Broodmother:
    - 0
    - 1
    Centaur Warrunner:
    - 0
    Chaos Knight:
    - 0
    - 1
    Chen:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Clinkz:
    - 0
    - 1
    Clockwerk:
    - 0
    - 1
    - 2
    - 3
    - 4
    Crystal Maiden:
    - 0
    - 1
    - 2
    - 3
    Dark Seer:
    - 0
    - 1
    Dark Willow:
    - 0
    - 1
    Dawnbreaker:
    - 0
    - 1
    Dazzle:
    - 0
    - 1
    - 2
    - 3
    Death Prophet:
    - 0
    - 1
    - 2
    Disruptor:
    - 0
    - 1
    - 2
    Doom:
    - 0
    - 1
    - 2
    Dragon Knight:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Drow Ranger:
    - 0
    - 1
    - 2
    - 3
    - 4
    Earth Spirit:
    - 0
    - 1
    Earthshaker:
    - 0
    Elder Titan:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Ember Spirit:
    - 0
    - 1
    - 2
    - 3
    - 4
    Enchantress:
    - 0
    - 1
    Enigma:
    - 0
    - 1
    - 2
    Faceless Void:
    - 0
    - 1
    - 2
    - 3
    - 4
    Grimstroke:
    - 0
    Gyrocopter:
    - 0
    - 1
    Hoodwink:
    - 0
    - 1
    - 2
    - 3
    Huskar:
    - 0
    Invoker:
    - 0
    - 1
    - 2
    - 3
    - 4
    Jakiro:
    - 0
    - 1
    - 2
    - 3
    - 4
    Juggernaut:
    - 0
    Keeper of the Light:
    - 0
    - 1
    Kunkka:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Legion Commander:
    - 0
    - 1
    Leshrac:
    - 0
    - 1
    - 2
    - 3
    - 4
    Lich:
    - 0
    - 1
    - 2
    - 3
    - 4
    Lifestealer:
    - 0
    Lina:
    - 0
    Lion:
    - 0
    - 1
    - 2
    - 3
    Lone Druid:
    - 0
    Luna:
    - 0
    Lycan:
    - 0
    Magnus:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Mars:
    - 0
    - 1
    - 2
    - 3
    Medusa:
    - 0
    Meepo:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Mirana:
    - 0
    Monkey King:
    - 0
    Morphling:
    - 0
    Naga Siren:
    - 0
    - 1
    Nature's Prophet:
    - 0
    - 1
    - 2
    Necrophos:
    - 0
    - 1
    Night Stalker:
    - 0
    - 1
    - 2
    Nyx Assassin:
    - 0
    - 1
    - 2
    - 3
    Ogre Magi:
    - 0
    Omniknight:
    - 0
    - 1
    - 2
    - 3
    Oracle:
    - 0
    Outworld Destroyer:
    - 0
    - 1
    - 2
    Pangolier:
    - 0
    - 1
    - 2
    - 3
    Phantom Assassin:
    - 0
    - 1
    - 2
    - 3
    Phantom Lancer:
    - 0
    - 1
    - 2
    Phoenix:
    - 0
    - 1
    - 2
    - 3
    Puck:
    - 0
    Pudge:
    - 0
    - 1
    - 2
    - 3
    - 4
    Pugna:
    - 0
    - 1
    Queen of Pain:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Razor:
    - 0
    - 1
    - 2
    - 3
    Riki:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Rubick:
    - 0
    - 1
    Sand King:
    - 0
    Shadow Demon:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Shadow Fiend:
    - 0
    - 1
    Shadow Shaman:
    - 0
    Silencer:
    - 0
    - 1
    - 2
    - 3
    Skywrath Mage:
    - 0
    Slardar:
    - 0
    - 1
    - 2
    - 3
    Slark:
    - 0
    Snapfire:
    - 0
    - 1
    - 2
    Sniper:
    - 0
    - 1
    Spectre:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Spirit Breaker:
    - 0
    - 1
    - 2
    - 3
    Storm Spirit:
    - 0
    - 1
    - 2
    - 3
    - 4
    Sven:
    - 0
    - 1
    - 2
    - 3
    Techies:
    - 0
    - 1
    - 2
    - 3
    - 4
    Templar Assassin:
    - 0
    - 1
    - 2
    - 3
    - 4
    Terrorblade:
    - 0
    Tidehunter:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Timbersaw:
    - 0
    - 1
    Tinker:
    - 0
    - 1
    - 2
    - 3
    Tiny:
    - 0
    Treant Protector:
    - 0
    Troll Warlord:
    - 0
    Tusk:
    - 0
    - 1
    - 2
    - 3
    - 4
    Underlord:
    - 0
    - 1
    - 2
    Undying:
    - 0
    Ursa:
    - 0
    - 1
    - 2
    - 3
    Vengeful Spirit:
    - 0
    - 1
    - 2
    - 3
    Venomancer:
    - 0
    - 1
    - 2
    - 3
    Viper:
    - 0
    - 1
    - 2
    Visage:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Void Spirit:
    - 0
    - 1
    - 2
    - 3
    Warlock:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Weaver:
    - 0
    Windranger:
    - 0
    - 1
    Winter Wyvern:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    Witch Doctor:
    - 0
    - 1
    - 2
    - 3
    - 4
    Wraith King:
    - 0
    - 1
    - 2
    Zeus:
    - 0
  steam_path: C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game
  view_resizable: true
  width: 1280
